import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";
import { cn } from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <Head>
          <script type="text/javascript">
            {` document.documentElement.classList.add('dark');`}
          </script>
        </Head>
        <body
          className={cn(
            inter.className,
            "bg-white dark:bg-black dark:text-white"
          )}
        >
          {children}
        </body>
      </html>
    </>
  );
}
